name: Build and deploy Node.js app to Azure Web App - coltiumindustriesv1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and run tests
        run: |
          npm ci
          npm run test --if-present

      - name: Build Next.js application
        run: npm run build

      - name: Verify build output
        run: |
          echo "Checking .next folder:"
          ls -la .next/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            .next
            package.json
            package-lock.json
            next.config.js
            public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_329DD404F3A34486972171F42592BC54 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_41551C07B80B4BBAA5658B38439C1228 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9616D6027F944BE3BD0E43D011A36FF9 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'coltiumindustriesv1'
          slot-name: 'Production'
          package: .
